apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: frontend
        image: marwanbarhoumi/site-ecommerce:latest  # À remplacer par Jenkins
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80