export const GET_COMMANDE = "GET_COMMANDE";
export const GET_COMMANDES_FAIL = "GET_COMMANDES_FAIL";
export const COMMANDES_LOADING = "COMMANDES_LOADING";

export const ADD_COMMANDE = "ADD_COMMANDE";
export const ADD_COMMANDE_FAIL = "ADD_COMMANDE_FAIL";
export const DELETE_COMMANDE = "DELETE_COMMANDE";
export const DELETE_COMMANDE_FAIL = "DELETE_COMMANDE_FAIL";
export const SET_LOADING = "SET_LOADING";
export const COMMANDE_LOADING = 'COMMANDE_LOADING';
export const COMMANDE_SUCCESS = 'COMMANDE_SUCCESS';
export const COMMANDE_FAIL = 'COMMANDE_FAIL';
export const RESET_COMMANDE = 'RESET_COMMANDE';