version: '3.8'

services:
  frontend:
    image: marwen77/frontend:latest
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # React app servie par Nginx (port 80 dans le conteneur)
    restart: always
    environment:
      - NODE_ENV=production
