version: '3'
services:
  login-service:
    build: ./backend/login
    ports:
      - "3001:3000"
    env_file: .env

  product-service:
    build: ./backend/product
    ports:
      - "3002:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"