alertmanager:
  enabled: false

pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: true
