global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'product'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.56.101:7100']

 
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.101:9090']

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['192.168.56.101:9093']
