apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: marwen77/gateway-service:latest
        ports:
        - containerPort: 7000  # Doit correspondre au port de votre application
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOGIN_SERVICE_URL  # Ajoutez ces variables
          value: "http://login-service:80"
        - name: VALIDATE_EMAIL
          value: "false"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:80"
        - name: USER_SERVICE_URL
          value: "http://user-service:80"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5