apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: memoire-ecommerce
  labels:
    app: gateway
    tier: backend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7000"
    spec:
      containers:
      - name: gateway
        image: marwen77/gateway-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: http
        env:
        - name: PORT
          value: "7000"
        - name: NODE_ENV
          value: "production"
        - name: LOGIN_SERVICE_URL
          value: "http://login-service.memoire-ecommerce.svc.cluster.local"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service.memoire-ecommerce.svc.cluster.local"
        - name: USER_SERVICE_URL
          value: "http://user-service.memoire-ecommerce.svc.cluster.local"
        - name: FRONTEND_URL
          value: "http://frontend-service.memoire-ecommerce.svc.cluster.local"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /gateway-status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /gateway-status
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /gateway-status
            port: http
          failureThreshold: 30
          periodSeconds: 10
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL