apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: memoire-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: marwen77/gateway-service:latest
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"  
        - name: NODE_ENV
          value: "production"
        - name: LOGIN_SERVICE_URL
          value: "http://login-service.memoire-ecommerce.svc.cluster.local:80"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service.memoire-ecommerce.svc.cluster.local:80" 
        - name: USER_SERVICE_URL
          value: "http://user-service.memoire-ecommerce.svc.cluster.local:80"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /  # Utilisez la racine si /health n'existe pas
            port: 7000
          initialDelaySeconds: 45  # Augmenté pour Node.js
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5