apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort  # Pour Minikube, LoadBalancer ne fonctionnera pas
  ports:
  - port: 80
    targetPort: 7000  # Doit matcher containerPort
    nodePort: 30000   # Port optionnel spécifique
  selector:
    app: gateway