apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: memoire-ecommerce
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: marwen77/gateway-service:latest
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: NODE_ENV
          value: "production"
        # Configuration des URLs des services internes
        - name: LOGIN_SERVICE_URL
          value: "http://login-service.memoire-ecommerce.svc.cluster.local:80"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service.memoire-ecommerce.svc.cluster.local:80"
        - name: USER_SERVICE_URL
          value: "http://user-service.memoire-ecommerce.svc.cluster.local:80"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        # Probes adaptées à votre code existant
        livenessProbe:
          httpGet:
            path: /gateway-status  # Utilise votre endpoint existant
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /gateway-status  # Utilise le même endpoint
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /gateway-status
            port: 7000
          failureThreshold: 30  # 30 x 10s = 5 minutes max
          periodSeconds: 10