apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: memoire-ecommerce
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000  # Correspond au containerPort
      nodePort: 30001