export const LOADING = "LOADING";
export const FAILD = "FAILD";
export const GETALLPRODUCTSSUCCESS = "GETALLPRODUCTSSUCCESS";
export const GETONEPRODUCTSSUCCESS = "GETONEPRODUCTSSUCCESS";
export const ADDPRODUCTSUCCESS = "ADDPRODUCTSUCCESS";
export const DELETEPRODUCTSUCCESS = "DELETEPRODUCTSUCCESS";
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';
