version: '3'
services:
  login-service:
    image: marwen77/login-service:latest
    ports:
      - "7010:7002"
    environment:
      - NODE_ENV=production
      - PORT=7002
      - mongourl=mongodb://mern:mern@cluster0-shard-00-00.ie7me.mongodb.net:27017,cluster0-shard-00-01.ie7me.mongodb.net:27017,cluster0-shard-00-02.ie7me.mongodb.net:27017/mern?ssl=true&replicaSet=atlas-xxxxxx-shard-0&authSource=admin&retryWrites=true&w=majority
