pipeline {
    agent any

    environment {
        DOCKER_HUB_USER = 'marwen77'
        DOCKER_HUB_PASSWORD = credentials('docker-hub-credentials-id') // Remplace par ton ID
    }

    stages {
        stage('Cloner le dépôt') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/marwanbarhoumi/memoire-Ecommerce.git',
                    credentialsId: '0d81d621-69e2-42f1-9117-821cbce06f5b'
            }
        }

        stage('Installer les dépendances') {
            steps {
                sh 'npm install --prefix frontend'
                sh 'npm install --prefix backend'
            }
        }

        stage('Lancer les tests') {
            steps {
                
                sh 'npm test --prefix backend || true'
            }
        }

        stage('Build des images Docker') {
            steps {
                sh 'docker build -t marwen77/frontend-app ./frontend'
                sh 'docker build -t marwen77/backend-api ./backend'
            }
        }

        stage('Push vers Docker Hub') {
            steps {
                withDockerRegistry([ credentialsId: 'docker-hub-credentials-id', url: '' ]) {
                    sh 'docker push marwen77/frontend-app'
                    sh 'docker push marwen77/backend-api'
                }
            }
        }

        stage('Déploiement avec Docker Compose') {
            steps {
                sh 'docker-compose down || true'
                sh 'docker-compose up -d'
            }
        }
    }
}
