apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login-service
  ports:
  - protocol: TCP
    port: 7002
    targetPort: 7002
  type: NodePort  # ou LoadBalancer si tu utilises un cloud
