apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login-service
  ports:
    - protocol: TCP
      port: 80          # Port exposé du service (interne au cluster)
      targetPort: 3000  # Port du container dans le pod
  type: ClusterIP      # Service accessible uniquement dans le cluster
