apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'frontend'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['frontend-service:3000']
    ```
