name: Build and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify files
      run: |
        ls -la  # Affiche la structure des fichiers
        pwd     # Montre le répertoire courant

    - name: Build
  working-directory: ./client
  run: docker build -t frontend-ecommerce .
        
    - name: Run container
      run: |
        docker run -d -p 3000:80 --name front-container frontend-ecommerce