apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7002
      nodePort: 31810
