jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Naviguer vers backend/login
        working-directory: ./backend/login  # <-- Clé importante !
        run: |
          ls -la  # Affiche les fichiers pour débogage
          npm install
          npm run build