name: Build and Push Docker 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Dockerfile exists
        run: |
          ls -la
          if [ ! -f "Dockerfile" ]; then
            echo "::error::Dockerfile not found!"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          # Pour les Pull Requests
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            docker build \
              -t marwen77/mysiteweb:pr-${{ github.event.number }} \
              -f Dockerfile .
          
          # Pour les pushes sur main
          else
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -t marwen77/mysiteweb:latest \
              -t marwen77/mysiteweb:${{ github.sha }} \
              -f Dockerfile \
              --push .
          fi